import = ["/home/prakhar/.config/alacritty/colors.toml", "/home/prakhar/.config/alacritty/fonts.toml"]
live_config_reload = true

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"

[window]
decorations = "none"
dynamic_title = true
# history = 10000
# multiplier = 3
opacity = 0.9
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 25

[window.padding]
x = 12
y = 12
